# Generated by Django 4.2.30 on 2026-04-13 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('catering_a', 'Catering – Proveedor A'), ('catering_b', 'Catering – Proveedor B'), ('stripe', 'Pago – Stripe'), ('paypal', 'Pago – PayPal'), ('mercadopago', 'Pago – MercadoPago'), ('youtube', 'Streaming – YouTube'), ('vimeo', 'Streaming – Vimeo'), ('facebook', 'Streaming – Facebook Live')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('api_key', models.CharField(blank=True, help_text='API key / credentials (simulated)', max_length=300)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='es_compuesto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subeventos', to='web.evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='ServicioContratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('respuesta_adapter', models.JSONField(blank=True, default=dict)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_contratados', to='web.evento')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='web.proveedorservicio')),
            ],
        ),
    ]
