# Generated by Django 4.2.30 on 2026-04-15 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_add_composite_adapter_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasarela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mercadopago', 'MercadoPago')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='💳', max_length=10)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='monto_pagado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesada', 'Procesada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('referencia_externa', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='web.evento')),
                ('pasarela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='web.pasarela')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
