# Generated by Django 4.2.30 on 2026-04-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_seed_pasarelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
